#this is a comment
#this is the rule list
#good luck.
#rule downloader:
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/domainset/cdn.conf
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/domainset/download.conf
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/ip/download.conf
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/ip/stream.conf
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/non_ip/cdn.conf
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/non_ip/stream.conf
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GlobalMedia/GlobalMedia.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Apkpure/Apkpure.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/BBC/BBC.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Bahamut/Bahamut.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/DiscoveryPlus/DiscoveryPlus.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Disney/Disney.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Dropbox/Dropbox.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Dubox/Dubox.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/FOXNOW/FOXNOW.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/FOXPlus/FOXPlus.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/GoogleDrive/GoogleDrive.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/HBOAsia/HBOAsia.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/HBOHK/HBOHK.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/HBOUSA/HBOUSA.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/HuluJP/HuluJP.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/HuluUSA/HuluUSA.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/KKTV/KKTV.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/MEGA/MEGA.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/NaverTV/NaverTV.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Netflix/Netflix.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Niconico/Niconico.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/NowE/NowE.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/OneDrive/OneDrive.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Overcast/Overcast.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/PandoraTV/PandoraTV.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ParamountPlus/ParamountPlus.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Peacock/Peacock.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/PrimeVideo/PrimeVideo.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/SourceForge/SourceForge.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Spotify/Spotify.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/TVer/TVer.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/TikTok/TikTok.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/YouTube/YouTube.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/YouTubeMusic/YouTubeMusic.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/myTVSUPER/myTVSUPER.list
