#this is a comment
#this is the rule list
#good luck.
#rule downloader:
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/domainset/reject.conf
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/domainset/reject_sukka.conf
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/ip/reject.conf
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/non_ip/reject.conf
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/non_ip/sogouinput.conf
https://raw.githubusercontent.com/an0na/R/master/Filter/AdBlock.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/AdvertisingLite/AdvertisingLite.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Privacy/Privacy.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/ZhihuAds/ZhihuAds.list
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Hijacking/Hijacking.list
https://raw.githubusercontent.com/ddgksf2013/Cuttlefish/master/Filter/Mybreak.list
https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo.list
https://raw.githubusercontent.com/scomper/surge-list/master/adblock.list
https://raw.githubusercontent.com/28413761/QX/main/fenliu.list
