#this is a comment
#this is the rule list
#good luck.
#rule downloader:
https://raw.githubusercontent.com/DoingDog/rconvert/main/static/mydirect.txt
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/ip/domestic.conf
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/non_ip/direct.conf
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/non_ip/domestic.conf
https://raw.githubusercontent.com/SukkaW/Surge/gh-pages/List/non_ip/my_direct.conf
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/China/China.list
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AccelerateDirectSites.list
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/CN.list
