name: make rules
on:
  schedule:
    - cron: '0 22 */3 * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        continue-on-error: false
        timeout-minutes: 10
        with:
          ref: main
      - name: run main
        continue-on-error: false
        timeout-minutes: 20
        run: |
          .\r.cmd a2
          .\r.cmd a1
          .\r.cmd cdn
          .\r.cmd big-data
          .\r.cmd dirt
      - name: commit
        continue-on-error: false
        timeout-minutes: 10
        run: |
          git init
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan main
          git add .
          git commit -m "Last Update at $(date +"%Y-%m-%d %H:%M")"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin main
